### PR TITLE
Remove SessionStealer

### PR DESCRIPTION
**Pull request by ghost**
You know, Mojang broke session stealer.

### CODE REVIEW

**Comment by lotsa-spaghetti** [comment]
Why closed?

**Comment by ghost** [comment]
I don't know.

**Comment by Alexander01998** [comment]
> Why closed?

Because it still works. It may be a little harder to find session IDs now, but that's not a reason to entirely remove it.

**Comment by lotsa-spaghetti** [comment]
I thought Session IDs now only work on the IP the created the session, so
even the not censored ones will not work unless you have the same IP, which
cannot be done.

**Comment by pokeball99** [comment]
@kim-yannick i think you can spoof your ip, and maybe you could set up a server where you get your victim's ip, then do social engineering to get the ID(say you need it to do some crap) and bam
but this is very likely a legal gray area, or illegal

**Pull request closed without merging**
