### PR TITLE
Added 1.9.X Protocol

### PR DESCRIPTION
**Pull request by Hexeption**
Added into GuiConnecting & SPacketJoinGame

Don't know what happened to the other files xD

### CODE REVIEW

**Comment by ghost** [comment]
Same thing happens, with the same files for me.
screen shot 2016-05-10 at 16 46 51

**Comment by ghost** [comment]
@Hexeption Also, could you please add [1.9.4](http://mojang.com/2016/05/minecraft-193/) too?

**Comment by Hexeption** [comment]
Sure i will do it now

**Comment by Hexeption** [comment]
Added 1.9.4 Support

**Comment by Alexander01998** [comment]
I don't know what you did there, but that definitely broke something:

image

Please just send me the changes that you made to the vanilla MC code and I will make a proper patch out of it.

**Comment by Alexander01998** [comment]
OK, I'll do that.

**Comment by Alexander01998** [comment]
I'll keep it open for now as a reminder and close it when it's done.

**Comment by Hexeption** [comment]
Okay

**Comment by Alexander01998** [comment]
I tried this on a couple of 1.9.2 servers and it doesn't seem to be working.This is the error that I'm getting:

image

Any ideas?

**Comment by Alexander01998** [comment]
Nevermind, I got it. You have to read 10 bytes, not 7.

**Comment by GitHub-BugSmasher** [comment]
Removed comment

**Pull request closed without merging**
