### PR TITLE
ExtraElytra mod

### PR DESCRIPTION
**Pull request by vovanre**
Rude sketch. Video: https://youtu.be/fU0EwgIAwK8

Resolves Wurst-Imperium/Wurst-Client-Bugs#42

### CODE REVIEW

**Comment by BrainyBrian** [comment]
Looking forward :)

**Comment by dgramop** [comment]
You should mention @Alexander01998 when you are done?

**Comment by Vertex-Client** [comment]
Lookin' good, @Alexander01998. :)

**Comment by Alexander01998** [comment]
> You should mention @Alexander01998 when you are done?

No, you shouldn't.

**Comment by dgramop** [comment]
@Alexander01998 My bad... I thought you wanted to be notified every time we make a pull and are ready... But I guess that was just for me because my code wasn't ready for deployment :D.

**Pull request merged**
