### PR TITLE
TrueSight works now

### PR DESCRIPTION
**Pull request by liach**
Pictures say all:

TrueSight can see hidden entities now, fixes Wurst-Imperium/Wurst-Client-Bugs#34

### CODE REVIEW

**Comment by ThisTestUser** [comment]
So Mineplex shows the invisible entities to the client? Because other servers like HiveMC don't, so this is only for Mineplex.
Also, you are changing isinvisible. This would break a lot of things that use this function and therefore is not the best way to implant it.

**Comment by Alexander01998** [comment]
> Also, you are changing isinvisible. This would break a lot of things that use this function and therefore is not the best way to implant it.

And it's also not the way how TrueSight is supposed to work.

**Comment by liach** [comment]
Then how? A [litemod](https://github.com/EasyMFnE/Omniscience) showing invisible entities works at all without additional impacts. It works in the same way, that it rewrites this method. Whatever @ThisTestUser could give a proper fix, right?

**Comment by liach** [comment]
I have not tested this for hive yet! Doesn't mean it does not work.

**Pull request closed without merging**
