### PR TITLE
LeetSpeak mod

### PR DESCRIPTION
**Pull request by ghost**
Replaces some character with funny leet characters.

### CODE REVIEW

**Comment by liach** [comment]
Could you just change the chat content randomly instead of always changing them?

**Comment by kmddd59** [comment]
Can you send me a way to do this please I'll like that a lot and if you add it to the next beta to add it to a cmd id love it

**Comment by mcccs** [comment]
It'll come if @Alexander01998 accepts it.

**Comment by mcccs** [comment]
@Alexander01998 @kim-yannick I have a trailer idea for Wurst and I can do it (In Blender). What do you think?

**Comment by liach** [comment]
@Alexander01998 I do not think this really works since this does not necessarily add a field for the mod in ModManager

**Comment by ghost** [comment]
Yep @liach 

And there's no reason for this PR to stay open, this branch is lost.

**Pull request closed without merging**
