### PR TITLE
Remove Flight Kick Bypass

### PR DESCRIPTION
**Pull request by lotsa-spaghetti**
1.9 fixed that...

### CODE REVIEW

**Comment by ghost** [comment]
I can confirm that.

Also, @kim-yannick if you're looking for something to implement i have an idea. It's about spamming packets again. This one should spam Keep Alive packets. When the player connects to Mineplex server (This hack is Mineplex only) and plays a game, after the game it says 300% gem: online for 3 hours. If you don't shut down the computer for a day, it'll say 2400% gems. Yay!

**Comment by lotsa-spaghetti** [comment]
@mcccs I don't think spamming keep alive packets modifies the server's time. Also, I think keep alive is just a response to the server's request, so spamming them is useless. http://wiki.vg/Protocol#Keep_Alive_.28clientbound.29

**Comment by ghost** [comment]
@kim-yannick you didn't understand me.. mineplex gives extra gems if you are more than an hour online. 1 hour : 100% more gems.

**Comment by lotsa-spaghetti** [comment]
Yes, but you can't modify the server's clock.

**Comment by ghost** [comment]
@kim-yannick You really didn't understand me... I'm not trying to modify the clock. Go to Mineplex Lobby and play a game. When the game ends, go to lobby and wait 20 minutes, then play a game. it'll say:

vvvv
15 + Gems for participation.
33% + gems for 20 minutes online!
vvvv

The cheat should send KeepAlive packets, to start timer.
screen shot 2016-03-20 at 10 16 48
When you press Launch MC it should give your session id to MC.

**Comment by lotsa-spaghetti** [comment]
So its just something that runs in the background without starting MC? Why
don't just stay on Mineplex?

**Comment by ghost** [comment]
Yea, that's a better idea.

**Comment by lotsa-spaghetti** [comment]
https://www.youtube.com/watch?v=lNvoWR0LFSc

Killaura seems to be like a NCP compatible regen
And Regen seems to work on NCP...

**Comment by Alexander01998** [comment]
> https://www.youtube.com/watch?v=lNvoWR0LFSc
> 
> Killaura seems to be like a NCP compatible regen
> And Regen seems to work on NCP...

Err... wut?

**Comment by lotsa-spaghetti** [comment]
It seems like the facing packet also causes faster regen. It seems that
regen still works on the latest NCP version, even if it gets detected, it
will still do nothing against it.
Am 21.03.2016 21:41 schrieb "Alexander01998" notifications@github.com:

**Pull request merged**
