### PR TITLE
AutoArmor Bug

### PR DESCRIPTION
**Pull request by nerdtron123**

### CODE REVIEW

**Comment by Alexander01998** [comment]
That's not a fix.

**Comment by nerdtron123** [comment]
Yeah, How can I get the MCP Lib?

**Comment by Alexander01998** [comment]
> Yeah, How can I get the MCP Lib?

https://www.wurst-client.tk/wiki/Contributing/part1/

**Comment by nerdtron123** [comment]
That's 1.8 I need the 1.9 one

**Comment by Alexander01998** [comment]
> That's 1.8 I need the 1.9 one

My libs haven't changed since Minecraft 1.8.X. I just add Slick2D and that's it.

**Pull request closed without merging**
