### PR TITLE
MassMSG fixed by vovanre

### PR DESCRIPTION
**Pull request by ghost**
Fix credits  : https://gist.github.com/vovanre/30ba1290349ac8a3e0d302f1e29beff7

### CODE REVIEW

**Comment by vovanre** [comment]
Hrmm, what makes this mod? I stubbornly refused to understand.

**Comment by vovanre** [comment]
... and I just correct syntax errors in your code.

**Comment by ghost** [comment]
Command
`/massmsg /w Looking for a server to play? Join Now! IP: MINEPLEX.ROCKS`
Players in the server:
User1
User2
User3
You

Commands typed by Wurst:
/w User1 Looking for a server to play? Join Now! IP: MINEPLEX.ROCKS
/w User2 Looking for a server to play? Join Now! IP: MINEPLEX.ROCKS
/w User3 Looking for a server to play? Join Now! IP: MINEPLEX.ROCKS

^^
This explains the usage of it, at least what I implemented in #13.

**Comment by dgramop** [comment]
Wait a second... #30

**Comment by dgramop** [comment]
Hope I got better quality? 
added a gui
Superseded by #30 
- You can remove this I guess?

**Pull request closed without merging**
