### PR TITLE
Better Step

### PR DESCRIPTION
**Pull request by 1zun4**

### CODE REVIEW

**Comment by ghost** [comment]
I guess @Alexander01998 can't test this pull request because **now he's busy with developer of LiquidBounce** because its developer is a copycat. If the world was full of contributors instead of **illegal stealers** the world would be a better place.

**Comment by Marco-MC** [comment]
ok

**Comment by SenkJu** [comment]
@mcccs You are trying to force @Alexander01998 to implement our work (BedGodMode, BoatSpeed and CrashHead) into Wurst. And you are developing a "private" version of Wurst which modules are 100% skidded. However, you want everybody to contribute own code? You are so stupid...

**Comment by Eyremba** [comment]
@mcccs 

"If the world was full of contributors instead of illegal stealers the world would be a better place."

This statement is just BULLSHIT.

ALL HackClient developers are STEALING tons of code from Mojang.
And because of the Minecraft EULA, you can NOT have a copyright in Minecraft because ALL copyright goes to Mojang.

So everybody can steal code, copy it, make his own client with it etc. this is all LEGAL.

The onliest way to "protect" your code is keeping it closed source and obfuscation.

**Comment by Alexander01998** [comment]
@Eyremba Listen, I know this is your opinion and I shouldn't care, but you are going against the law with that.

Wurst has a license, I have a lawyer, the Wurst-Imperium is registered as a business, all that stuff is there.

I mean, if you think Wurst doesn't have copyright protection on it, that's fine, I don't care what you think. But if you try to steal my code, you are very much going get in trouble.

**Comment by Eyremba** [comment]
@Alexander01998 First, I'm not a java coder, so I am not stealing your code, and I never said this, this is just a discussion with @mcccs about obfuscating, you can also see it here: https://github.com/mcccs/Wurst-Client-for-MC-1.9.X/commit/dd8e8a21ad197bd0025045221405ba81e6cb3f0b

And at least, remeber that also Mojang can get you in trouble because the Mojang EULA does not allow modified clients like Hackclients.

**Pull request closed without merging**
